### ISSUE TITLE
Add officially supported docker image (or endorsed community)

### ISSUE THREAD

**Issue by nathang21** [bitcoinknots/bitcoin#109]
Docker is a common way to run software with minimal configuration required on the host OS. Unfortunately, from what I can tell there are no well-maintained bitcoin knots images, all the ones that I could find are 2+ years out of date.
- [github.com/nolim1t/docker-bitcoinknots](https://github.com/nolim1t/docker-bitcoinknots)

For comparison, bitcore core has many popular and well maintained images such as the following:
- [hub.docker.com/r/bitcoin/bitcoin](https://hub.docker.com/r/bitcoin/bitcoin) - Monthly updates
- [hub.docker.com/r/lncm/bitcoind](https://hub.docker.com/r/lncm/bitcoind) - Release cycle updates

While end-users could build an image themselves via something like this (or make their own), this adds maintenance burden to keep the image updated with security patches, and bitcoin knots client releases. 
- [github.com/gobrrrme/bitcoind_quick](https://github.com/gobrrrme/bitcoind_quick)

**Comment by DecentralizedRebel** [comment]
As a refugee from [this Bitcoin Core PR](https://github.com/bitcoin/bitcoin/pull/32359#issuecomment-2833660649) I would fit right in on the user story of having to replace one of the well maintained images above, hence the upvote.

I'd love to have a simple, trustworthy drop-in knots replacement to switch the from one of the Bitcoin Core images mentioned above.

**Comment by dr0ther** [comment]
I have a V28.1 version of knots docker if anyone wants to use it:
https://github.com/dr0ther/bitcoin-knots-docker
or you can pull it from dockerhub
drother/bitcoinknots:latest

**Comment by nathang21** [comment]
Thanks for sharing, that looks like a great start, however without an automated CI setup, the image will become stale and include potential security vulnerabilities. Let me know if you want some help with that.

**Comment by dr0ther** [comment]
Oh for sure....I just spun that up over the weekend given the current drama over Core, and I'm a huge fan of containers. I thought it might give someone better than me a head start.

**Comment by DecentralizedRebel** [comment]
yes, I might also be available for some CI automation as well if it's needed, tough I've mostly used GitLab and Renovate Bot for such automated maintenance before. From the top of my head, at the very least I suggest we should try to ensure verifiability and a proper builds by

- Using build stages in the Dockerfile, to make sure the released image have no bloat
- Make it multi arch, at the very least x86 and ARM64 (Raspberry Pi)
- Query the releases to ensure the latest current release is used for the build (example: `curl -s https://api.github.com/repos/bitcoinknots/bitcoin/releases/latest | jq .tag_name`)
- Verify the downloaded assets `gpg --verify SHA256SUMS.asc && sha256sum --check SHA256SUMS --ignore-missing ` (perhaps there's a better way to do this?)
- I'd also like to have some example `compose.yml` files with default setups

**Comment by nathang21** [comment]
+1 that seems like a great list to start. I might take a stab at this when I get a chance, for now @dr0ther's image above has worked for me, I was able to migrate without loosing any state, via some minor confirmation changes to my compose file. Sharing before and after here for reference if it helps others. 

```
  # Bitcoin Core
  bitcoin-core:
    container_name: bitcoin-core
    user: "1000:1000"  # Non-root user for security
    image: lncm/bitcoind
    restart: always
    stop_grace_period: 15m30s
    ports:
      - "8333:8333"      # Bitcoin P2P
      - "8332:8332"      # RPC only accessible locally
    volumes:
      - ./state:/data/.bitcoin 
    labels:
      com.centurylinklabs.watchtower.enable: true
      autoheal: true
    environment:
      - BTC_EXTRA_ARGS=-server=1 -rpcuser=<REDACTED> -rpcpassword=<REDACTED> -rpcport=8332 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -maxconnections=125 -dbcache=4096 -maxmempool=500 -par=4 -prune=15000  # Pruned node (15GB)
```      
```
  # Bitcoin Knots (should be almost interchangeable with the above, as long as state dir is mapped correctly, and command parameters)
  bitcoin-knots:
    container_name: bitcoin-knots
    image: drother/bitcoinknots
    restart: always
    stop_grace_period: 15m30s
    ports:
      - "8333:8333"      # Bitcoin P2P
      - "8332:8332"      # RPC only accessible locally
    volumes:
      - ./state:/home/bitcoin/.bitcoin
    labels:
      com.centurylinklabs.watchtower.enable: true
      autoheal: true
    command:
      - bitcoind
      - -server=1
      - -rpcuser=<REDACTED>
      - -rpcpassword=<REDACTED>
      - -rpcport=8332
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -maxconnections=125
      - -dbcache=4096
      - -maxmempool=500
      - -par=4
      - -prune=15000
```
